ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "anniversary" TIMESTAMP(3);
ALTER TABLE "Visit" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Visit" ADD COLUMN IF NOT EXISTS "profession" TEXT;
ALTER TABLE "Visit" ADD COLUMN IF NOT EXISTS "anniversary" TIMESTAMP(3);
