export const content = {
  common: {
    appName: "FineSet",
    loading: "Loading…",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    export: "Export",
    search: "Search",
    filter: "Filter",
    noResults: "No results found",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    viewAll: "View all",
    signOut: "Sign out",
  },
  auth: {
    login: {
      title: "Sign in to FineSet",
      subtitle: "Use your work email and password",
      submitLabel: "Sign In",
      errorInvalid: "Invalid email or password",
      errorInactive:
        "Your account is not active. Open your invite email or contact your administrator.",
      errorGeneric: "You do not have access to this portal.",
      forgotPassword: "Forgot password?",
      resetSuccess: "Your password has been updated. Sign in with your new password.",
      forgotPasswordEmailRequired:
        "Enter your email first, then request a password reset link.",
      resetEmailSent:
        "If an account exists for that email, a password reset link has been sent. Check your inbox.",
      resetEmailError: "Could not send the reset email. Try again in a few minutes.",
      resetEmailRateLimited:
        "Too many reset requests. Please wait a few minutes and try again.",
    },
    resetPassword: {
      title: "Reset your password",
      subtitle: "Choose a new password for your account",
      passwordLabel: "New password",
      passwordPlaceholder: "Enter new password",
      confirmPasswordLabel: "Confirm password",
      confirmPasswordPlaceholder: "Re-enter new password",
      submitLabel: "Update password",
      backToSignIn: "Back to sign in",
      errorGeneric: "Could not update password. Try again.",
      errorMismatch: "Passwords do not match.",
      errorNoSession:
        "This reset link is invalid or has expired. Request a new one from the sign-in page.",
    },
    staff: {
      title: "Staff Login",
      subtitle: "Sign in to access the staff portal",
      idLabel: "Employee Name",
      idPlaceholder: "Enter employee name",
      passwordLabel: "Employee ID",
      passwordPlaceholder: "Enter employee ID",
      submitLabel: "Sign In",
      errorInvalid: "Invalid employee name or ID",
    },
    store: {
      title: "Store Login",
      subtitle: "Access your store dashboard",
      idLabel: "Store Name",
      idPlaceholder: "Enter store name",
      passwordLabel: "Store Pincode",
      passwordPlaceholder: "Enter store pincode",
      submitLabel: "Access Dashboard",
      errorInvalid: "Invalid store name or pincode",
    },
    admin: {
      title: "Consultant Login",
      subtitle: "Portfolio access for all client stores",
      idLabel: "Admin Email",
      idPlaceholder: "Enter admin email",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter password",
      submitLabel: "Sign In to Admin",
      errorInvalid: "Invalid admin credentials",
    },
  },
  visitForm: {
    title: "Log Customer Visit",
    subtitle: "Record visit details for analytics",
    schemeHint:
      "Primary goal: pitch Gold Harvest Scheme (GHS) and Gold Purchase Plan (GPP). Capture who you met and what was enrolled.",
    progress: "Step {current} of {total}",
    sections: {
      customer: "Customer Details",
      visit: "Visit Details",
      scheme: "Scheme Pitch & Outcome",
      noPurchase: "No-Purchase Context",
      preferences: "Product Preferences",
      followUp: "Follow-up",
    },
    fields: {
      customerName: { label: "Customer Name", placeholder: "Full name" },
      phone: { label: "Phone Number", placeholder: "10-digit mobile" },
      existingCustomerHint: "Existing customer — details prefilled",
      lookingUpCustomer: "Looking up customer…",
      customerType: {
        label: "Customer Type",
        options: { NEW: "New", REPEAT: "Repeat", VIP: "VIP" },
      },
      visitType: {
        label: "Visit Type",
        options: { WALK_IN: "Walk-in", APPOINTMENT: "Appointment" },
      },
      inTime: { label: "In Time", placeholder: "Select time" },
      outTime: { label: "Out Time", placeholder: "Select time" },
      totalDuration: { label: "Total Duration" },
      sourceChannel: {
        label: "Source / Channel",
        options: {
          ORGANIC_WALK_IN: "Organic Walk-in",
          REFERRAL: "Referral",
          SOCIAL_MEDIA: "Social Media",
          INTERNET: "Internet",
          PHONE: "Phone",
          USER_CALLS: "User Calls",
          TANISHQ_REF: "Tanishq Reference",
          CARATLANE_REF: "Caratlane Reference",
          OTHER: "Other",
        },
      },
      area: { label: "Area / Locality", placeholder: "Locality or area" },
      gender: {
        label: "Gender",
        options: {
          MALE: "Male",
          FEMALE: "Female",
          OTHER: "Other",
          PREFER_NOT_TO_SAY: "Prefer not to say",
        },
      },
      ageGroup: {
        label: "Age Group",
        options: {
          "18-25": "18–25",
          "26-35": "26–35",
          "36-50": "36–50",
          "50+": "50+",
        },
      },
      productsExplored: {
        label: "Products Explored",
        options: {
          RINGS: "Rings",
          NECKLACES: "Necklaces",
          BANGLES: "Bangles",
          EARRINGS: "Earrings",
          CHAINS: "Chains",
          PENDANTS: "Pendants",
          SETS: "Sets",
          OTHER: "Other",
        },
      },
      purchaseStatus: {
        label: "Purchase Status",
        options: {
          PURCHASED: "Purchased",
          NOT_PURCHASED: "Not Purchased",
        },
      },
      productsPurchased: { label: "Products Purchased" },
      transactionAmount: {
        label: "Transaction Amount",
        placeholder: "Amount in ₹",
      },
      intentTier: {
        label: "Interest Level",
        placeholder: "Select",
        options: {
          HOT: "Hot",
          WARM: "Warm",
          COLD: "Cold",
          BROWSING: "Browsing",
        },
      },
      schemesPitched: {
        label: "Schemes Pitched",
        options: {
          GHS: "GHS — Gold Harvest Scheme",
          GPP: "GPP — Gold Purchase Plan",
        },
      },
      enrollmentOutcome: {
        label: "Outcome",
        options: {
          ENROLLED_GHS: "Enrolled in GHS",
          ENROLLED_GPP: "Enrolled in GPP",
          ENROLLED_BOTH: "Enrolled in both",
          INTERESTED: "Interested — not enrolled yet",
          DECLINED: "Declined",
          CALLBACK: "Callback requested",
        },
      },
      monthlyCommitment: {
        label: "Monthly Commitment (₹)",
        placeholder: "Monthly installment amount",
      },
      reasonNoEnrollment: {
        label: "Reason",
        options: {
          BUDGET: "Budget constraints",
          ALREADY_ENROLLED: "Already enrolled elsewhere",
          NOT_INTERESTED: "Not interested",
          NEEDS_TIME: "Needs more time",
          TRUST_CONCERNS: "Trust / clarity concerns",
          COMPETITOR_SCHEME: "Competitor scheme",
        },
      },
      schemeCompetitorMention: {
        label: "Competitor / Alternative",
        placeholder: "Optional — other jeweller or scheme",
      },
      reasonNoPurchase: {
        label: "Reason No Purchase",
        options: {
          BUDGET: "Budget",
          DESIGN_NOT_LIKED: "Design not liked",
          EXPLORING: "Exploring",
          COMPETITOR: "Competitor",
          PAYMENT_ISSUE: "Payment issue",
          WILL_VISIT_AGAIN: "Will visit again",
        },
      },
      competitorMention: {
        label: "Competitor Mention",
        placeholder: "Optional competitor name",
      },
      purchaseOccasion: {
        label: "Purchase Occasion",
        options: {
          WEDDING: "Wedding",
          ANNIVERSARY: "Anniversary",
          GIFT: "Gift",
          SELF: "Self",
          FESTIVAL: "Festival",
        },
      },
      metalKtPref: {
        label: "Metal / KT Preference",
        options: {
          GOLD_18KT: "Gold 18KT",
          GOLD_22KT: "Gold 22KT",
          DIAMOND: "Diamond",
          PLATINUM: "Platinum",
          SILVER: "Silver",
        },
      },
      budgetStated: {
        label: "Budget Stated",
        options: {
          UNDER_15K: "Under ₹15K",
          K15_50K: "₹15K – ₹50K",
          K50_1L: "₹50K – ₹1L",
          ABOVE_1L: "Above ₹1L",
          NOT_STATED: "Not stated",
        },
      },
      followUpNeeded: { label: "Follow-up Needed" },
      followUpDate: { label: "Follow-up Date", placeholder: "Select date" },
      staffNotes: {
        label: "Staff Notes",
        placeholder: "Additional notes (max 500 characters)",
      },
    },
    actions: {
      submit: "Submit Visit",
      logAnother: "Log Another Visit",
      saving: "Saving…",
      successTitle: "Visit logged successfully",
      successMessage: "The visit has been recorded and synced.",
    },
    validation: {
      required: "This field is required",
      phoneInvalid: "Enter a valid 10-digit phone number",
      notesMaxLength: "Notes must be 500 characters or fewer",
      amountRequired: "Transaction amount is required for purchases",
    },
  },
  fieldSalesForm: {
    title: "Log Field Sale",
    subtitle:
      "Record outdoor customer interactions and GHS / GPP scheme outcomes",
    schemeHint:
      "Primary goal: pitch Gold Harvest Scheme (GHS) and Gold Purchase Plan (GPP). Capture who you met and what was enrolled.",
    progress: "Step {current} of {total}",
    sections: {
      customer: "Customer Details",
      activity: "Field Activity",
      scheme: "Scheme Pitch & Outcome",
      noEnrollment: "No-Enrollment Context",
      followUp: "Follow-up",
    },
    fields: {
      customerName: { label: "Customer Name", placeholder: "Full name" },
      phone: { label: "Phone Number", placeholder: "10-digit mobile" },
      customerType: {
        label: "Customer Type",
        options: { NEW: "New", REPEAT: "Repeat", VIP: "VIP" },
      },
      profession: {
        label: "Profession",
        placeholder: "e.g. Teacher, Business owner",
      },
      area: { label: "Area / Locality", placeholder: "Neighbourhood or territory" },
      gender: {
        label: "Gender",
        placeholder: "Select",
        options: {
          MALE: "Male",
          FEMALE: "Female",
          OTHER: "Other",
          PREFER_NOT_TO_SAY: "Prefer not to say",
        },
      },
      ageGroup: {
        label: "Age Group",
        placeholder: "Select",
        options: {
          "18-25": "18–25",
          "26-35": "26–35",
          "36-50": "36–50",
          "50+": "50+",
        },
      },
      activityType: {
        label: "Activity Type",
        options: {
          DOOR_TO_DOOR: "Door to door",
          HOUSING_SOCIETY: "Housing society",
          CORPORATE: "Corporate / office",
          EVENT_EXHIBITION: "Event / exhibition",
          MARKET_STALL: "Market stall",
          REFERRAL_MEET: "Referral meeting",
          OTHER: "Other",
        },
      },
      locationLabel: {
        label: "Location",
        placeholder: "e.g. Green Park Society, Block B",
      },
      activityDate: { label: "Activity Date" },
      startTime: { label: "Start Time" },
      endTime: { label: "End Time" },
      totalDuration: { label: "Total Duration" },
      schemesPitched: {
        label: "Schemes Pitched",
        options: {
          GHS: "GHS — Gold Harvest Scheme",
          GPP: "GPP — Gold Purchase Plan",
        },
      },
      enrollmentOutcome: {
        label: "Outcome",
        options: {
          ENROLLED_GHS: "Enrolled in GHS",
          ENROLLED_GPP: "Enrolled in GPP",
          ENROLLED_BOTH: "Enrolled in both",
          INTERESTED: "Interested — not enrolled yet",
          DECLINED: "Declined",
          CALLBACK: "Callback requested",
        },
      },
      monthlyCommitment: {
        label: "Monthly Commitment (₹)",
        placeholder: "Monthly installment amount",
      },
      intentTier: {
        label: "Interest Level",
        placeholder: "Select",
        options: {
          HOT: "Hot",
          WARM: "Warm",
          COLD: "Cold",
          BROWSING: "Browsing",
        },
      },
      reasonNoEnrollment: {
        label: "Reason",
        options: {
          BUDGET: "Budget constraints",
          ALREADY_ENROLLED: "Already enrolled elsewhere",
          NOT_INTERESTED: "Not interested",
          NEEDS_TIME: "Needs more time",
          TRUST_CONCERNS: "Trust / clarity concerns",
          COMPETITOR_SCHEME: "Competitor scheme",
        },
      },
      competitorMention: {
        label: "Competitor / Alternative",
        placeholder: "Optional — other jeweller or scheme",
      },
      followUpNeeded: { label: "Schedule follow-up" },
      followUpDate: { label: "Follow-up Date" },
      staffNotes: {
        label: "Staff Notes",
        placeholder: "Conversation highlights (max 500 characters)",
      },
    },
    actions: {
      submit: "Submit Field Sale",
      logAnother: "Log Another Interaction",
      saving: "Saving…",
      successTitle: "Field sale logged",
      successMessage: "Customer data and scheme outcome have been recorded.",
    },
  },
  staff: {
    shell: {
      title: "Staff Portal",
    },
    portal: {
      title: "What would you like to do?",
      subtitle: "Choose an action to get started",
      actions: {
        logVisit: {
          title: "Log Customer Visit",
          description: "Record walk-in or appointment details for store analytics",
          cta: "Log visit",
        },
        callUsers: {
          title: "Call Users",
          description: "Call customers you served and log retention outcomes",
          cta: "View call list",
        },
        fieldSales: {
          title: "Field Sales",
          description: "Log outdoor visits and GHS / GPP enrollments in the field",
          cta: "Log field sale",
        },
      },
    },
    calls: {
      back: "Back",
      title: "Call Users",
      subtitle: "Reconnect with customers you served to improve retention",
      yearLabel: "Year",
      monthLabel: "Month",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      queueLabel: "Call queue",
      segmentLabel: "Customer segment",
      valueTierLabel: "Ticket value",
      call: "Call",
      noPhone: "No phone on file",
      due: "Due",
      loadError: "Could not load customers. Sign out and sign in again, then retry.",
      noCustomersYet:
        "No customers to call yet. Log a customer visit first — they will appear here.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      queues: [
        { key: "ALL", label: "All customers" },
        { key: "RETENTION", label: "Retention calls" },
        { key: "FOLLOW_UP", label: "Follow-up calls" },
      ],
      segments: [
        { key: "ALL", label: "All" },
        { key: "NEW", label: "New" },
        { key: "RETAINED", label: "Retained" },
        { key: "PURCHASED", label: "Purchased" },
        { key: "NOT_PURCHASED", label: "Not purchased" },
      ],
      valueTiers: [
        { key: "ALL", label: "All values" },
        { key: "HIGH", label: "High value" },
        { key: "MID", label: "Mid value" },
        { key: "LOW", label: "Low value" },
      ],
      valueTierLabels: {
        HIGH: "High value",
        MID: "Mid value",
        LOW: "Low value",
      },
      purchaseStatusLabels: {
        PURCHASED: "Purchased",
        NOT_PURCHASED: "Not purchased",
        PENDING: "Pending",
      },
      customerTypeLabels: {
        NEW: "New",
        REPEAT: "Retained",
        VIP: "VIP",
      },
      queueStatusLabels: {
        RETENTION: "Retention",
        FOLLOW_UP: "Follow-up",
      },
      callOutcomeLabels: {
        ANSWERED: "Answered",
        NOT_ANSWERED: "Not answered",
        NOT_CALLED: "Not called yet",
      },
      notesLabel: "Notes",
      dialog: {
        title: "Call feedback",
        description: "Update the outcome for {name}",
        descriptionGeneric: "Update the call outcome",
        revealingPhone: "Fetching contact…",
        outcomeLabel: "Call outcome",
        answered: "Answered",
        notAnswered: "Not answered",
        feedbackLabel: "Call feedback",
        feedbackPlaceholder: "What did the customer say?",
        scheduleFollowUp: "Schedule follow-up",
        followUpDateLabel: "Follow-up date",
        notAnsweredNoteLabel: "Notes (optional)",
        notAnsweredNotePlaceholder: "Add context for the next attempt",
        notAnsweredHint: "This customer will move to your follow-up call queue.",
        saveOutcome: "Save outcome",
        saving: "Saving…",
        feedbackSaved: "Call outcome saved",
      },
    },
    fieldSales: {
      back: "Back",
    },
  },
  store: {
    nav: {
      overview: "Overview",
      visits: "Visits Log",
      calls: "Call Users",
      fieldSales: "Field Sales",
      staff: "Staff",
    },
    shell: {
      title: "Store Dashboard",
    },
    kpis: {
      totalVisits: "Total Visits",
      totalRevenue: "Total Revenue",
      conversionRate: "Conversion Rate",
      avgTransaction: "Avg Transaction",
      newCustomers: "New Customers",
      repeatCustomers: "Repeat Customers",
      openFollowUps: "Open Follow-ups",
    },
    period: {
      today: "Today",
      week: "This Week",
      month: "This Month",
      last3months: "Last 3 Months",
      last6months: "Last 6 Months",
    },
    deltaPeriod: "vs last period",
    businessOverview: {
      title: "Business Overview ({period})",
      subtitle:
        "Store-wide visits, revenue, conversion, and customer metrics at a glance.",
    },
    callsOverview: {
      title: "Call Users Overview ({period})",
      subtitle:
        "Track outbound follow-up calls, answer rates, staff effort, and note themes to improve retention.",
      empty: "No call activity recorded for this period",
      error: "Unable to load call analytics.",
      retry: "Retry",
      tabs: {
        overview: "Overview",
        segments: "Segments",
        team: "Team",
        notes: "Notes",
      },
      kpis: {
        totalCalls: "Total Calls",
        answered: "Answered",
        notAnswered: "Not Answered",
        answerRate: "Answer Rate",
        coverage: "Pool Coverage",
        callToConversion: "Call → Conversion",
        feedbackRate: "Notes Logged",
        activeStaff: "Active Callers",
        avgCallsPerStaff: "Avg Calls / Staff",
        storeVisitsFromCalls: "Store Visits (User Calls)",
        storeVisitsFromCallsConversion: "User Calls → Purchase",
      },
      highlights: {
        bestAnswerRate: "Best Answer Rate",
        needsAttention: "Needs Coaching",
      },
      charts: {
        staffVolume: "Calls per Staff",
        staffVolumeHint: "Who is driving follow-up volume",
        staffOutcome: "Staff Outcomes",
        staffOutcomeHint: "Answered vs unanswered by team member",
        byCustomerType: "By Customer Type",
        byPurchaseStatus: "By Purchase Status",
        byValueTier: "By Value Tier",
        byIntent: "By Intent Tier",
      },
      notes: {
        title: "Call Notes & Themes",
        subtitle:
          "Keyword themes from staff feedback; AI summary when Gemini API key is configured.",
        aiSummary: "AI summary",
        aiUnavailable:
          "Add GEMINI_API_KEY to .env.local for AI-generated call notes summary.",
        aiPending: "Not enough notes for an AI summary yet.",
        themes: "Common themes in notes",
        recentNotes: "Recent call notes",
      },
      table: {
        title: "Staff Call Breakdown",
        staff: "Staff",
        totalCalls: "Calls",
        answered: "Answered",
        notAnswered: "Unanswered",
        answerRate: "Answer %",
        callToConversion: "Call → Conv.",
        uniqueVisits: "Visits",
        feedback: "With notes",
      },
      viewInLog: "View in Call Users log",
      viewInLogHint: "Click a chart bar or staff row to open matching call records",
      exportCsv: "Export CSV",
    },
    fieldSalesOverview: {
      title: "Field Sales Overview ({period})",
      subtitle:
        "Track outdoor visits, areas covered, follow-ups, and enrollments to grow GHS/GPP business.",
      empty: "No field sales activity recorded for this period",
      error: "Unable to load field sales analytics.",
      retry: "Retry",
      tabs: {
        overview: "Overview",
        segments: "Segments",
        team: "Team",
        notes: "Notes",
      },
      kpis: {
        totalVisits: "People Visited",
        enrollmentRate: "Enrollment Rate",
        enrolled: "Enrolled",
        uniqueAreas: "Areas Covered",
        followUpRequired: "Follow-ups Required",
        followUpConversion: "Follow-up → Enrolled",
        interested: "Interested / Callback",
        declined: "Declined",
      },
      insights: {
        sectionTitle: "Field performance insights",
        sectionSubtitle:
          "Channel conversion, coaching signals, follow-up closure, and note themes to guide field strategy.",
        enrollmentByActivity: "Enrollment rate by activity type",
        enrollmentByActivityHint:
          "Compare housing society vs door-to-door and other channels — double down on high converters.",
        declineReasons: "Decline reasons (coaching)",
        declineReasonsHint:
          "Budget, trust, and competitor objections — use for coaching, offers, and rebuttals.",
        followUpConversion: "Follow-up → enrolled",
        followUpConversionHint:
          "Measures whether callbacks close — enrolled after a follow-up was required.",
        followUpConverted: "{converted} enrolled of {required} follow-ups required",
        intentTier: "Enrollment by intent tier",
        intentTierHint: "Prioritize hot leads in the field — spot where intent converts.",
        notesThemes: "Notes themes",
        notesThemesHint:
          "Objections and interest signals from staff notes (budget, trust, competitor, scheme interest).",
        noDeclineData: "No decline reasons recorded yet.",
        noNotesThemes: "No note themes yet — ask staff to log objections and interest in notes.",
      },
      highlights: {
        bestEnrollmentRate: "Best Enrollment Rate",
        needsAttention: "Needs Coaching",
      },
      charts: {
        outcomeSplit: "Enrollment Outcomes",
        outcomeSplitHint: "Enrolled vs pipeline vs lost for the period",
        dailyVolume: "Daily Field Activity",
        dailyVolumeHint: "Visits and enrollments by day",
        enrollmentTrend: "Daily Enrollment Rate",
        enrollmentTrendHint: "Spot days with stronger scheme conversion",
        byActivityType: "By Activity Type",
        byOutcome: "By Enrollment Outcome",
        byArea: "Top Areas Covered",
        byCustomerType: "By Customer Type",
        byIntent: "By Intent Tier",
        byDeclineReason: "Decline Reasons",
        followUpStatus: "Follow-up Status",
        followUpStatusHint: "Open, converted, and closed follow-ups from field visits",
        staffVolume: "Visits per Staff",
        staffVolumeHint: "Who is covering the most ground",
        staffOutcome: "Staff Enrollments",
        staffOutcomeHint: "Enrolled vs not enrolled by team member",
        segmentClickHint: "Click a bar to view matching field sales records",
      },
      notes: {
        title: "Field Notes & Themes",
        subtitle:
          "Keyword themes from staff notes; AI summary when Gemini API key is configured.",
        aiSummary: "AI summary",
        aiUnavailable:
          "Add GEMINI_API_KEY to .env.local for AI-generated field notes summary.",
        aiPending: "Not enough notes for an AI summary yet.",
        themes: "Common themes in notes",
        recentNotes: "Recent field notes",
      },
      table: {
        title: "Staff Field Sales Breakdown",
        staff: "Staff",
        totalVisits: "Visits",
        enrolled: "Enrolled",
        enrollmentRate: "Enroll %",
        followUpNeeded: "Follow-ups",
        followUpsConverted: "Converted",
        uniqueAreas: "Areas",
        notes: "With notes",
      },
      viewInLog: "View in Field Sales log",
      viewInLogHint: "Click a chart bar or staff row to open matching field records",
      exportCsv: "Export CSV",
    },
    rsoPerformance: {
      title: "RSO Revenue Performance ({period})",
      subtitle:
        "Compare RSO sales, conversion, scheme enrollments, and revenue growth for the store.",
      empty: "No RSO performance data for this period",
      error: "Unable to load RSO performance.",
      retry: "Retry",
      emptyHighlight: "Not enough data yet",
      highlights: {
        topPerformer: {
          title: "Top Performer",
        },
        mostImproved: {
          title: "Most Improved",
        },
      },
      charts: {
        staffRevenue: "Revenue by RSO",
        staffRevenueHint: "Who is driving the most revenue this period",
        staffConversion: "RSO Conversion Rate",
        staffConversionHint: "Purchase conversion by team member",
      },
      table: {
        title: "RSO Performance Breakdown",
        staff: "RSO Name",
        customersAttended: "Customers Attended",
        purchased: "Purchased",
        notPurchased: "Non Purchased",
        schemesEnrolled: "Schemes Enrolled",
        dataEntryScore: "DES score",
        growth: "Growth",
        revenue: "Revenue",
      },
      exportCsv: "Export CSV",
      columns: {
        rsoName: "RSO Name",
        customersAttended: "Customers Attended",
        purchased: "Purchased",
        notPurchased: "Non Purchased",
        schemesEnrolled: "Schemes Enrolled",
        dataEntryScore: "DES score",
        growth: "Growth",
        revenue: "Revenue",
      },
      topPerformer: {
        title: "Top Performer",
      },
      mostImproved: {
        title: "Most Improved",
      },
    },
    table: {
      showing: "Showing {from}–{to} of {total}",
      page: "Page {page}",
      yes: "Yes",
    },
    visits: {
      title: "Visits Log",
      filters: {
        all: "All Visits",
        followUpOnly: "Follow-up Only",
        startDate: "From Date",
        endDate: "To Date",
      },
      columns: {
        visitId: "Visit ID",
        date: "Date",
        inTime: "In Time",
        outTime: "Out Time",
        duration: "Duration",
        staff: "Staff",
        customer: "Customer",
        phone: "Phone",
        customerType: "Customer Type",
        type: "Visit Type",
        sourceChannel: "Source / Channel",
        area: "Area / Locality",
        gender: "Gender",
        ageGroup: "Age Group",
        status: "Purchase Status",
        productsExplored: "Products Explored",
        productsPurchased: "Products Purchased",
        revenue: "Revenue",
        intentTier: "Intent Tier",
        reasonNoPurchase: "Reason No Purchase",
        competitorMention: "Competitor Mention",
        purchaseOccasion: "Purchase Occasion",
        metalKtPref: "Metal / KT Preference",
        budgetStated: "Budget Stated",
        schemeEnrolled: "Scheme Enrolled",
        ghsPolicy: "GHS Policy",
        followUp: "Follow-up Needed",
        followUpDate: "Follow-up Date",
        followUpStatus: "Follow-up Status",
        notes: "Staff Notes",
        products: "Products",
      },
      detailTitle: "Visit Details",
      exportCsv: "Export CSV",
      sections: {
        customer: "Customer Details",
        visit: "Visit Details",
        noPurchase: "No-Purchase Context",
        preferences: "Preferences & Schemes",
        followUp: "Follow-up",
      },
    },
    staff: {
      title: "Staff Management",
      addStaff: "Add Staff",
      accountCreated:
        "Staff account created. Share their work email and password so they can sign in.",
      inviteSent: "Invitation email sent. They will set their own password.",
      columns: {
        name: "Name",
        employeeId: "Employee ID",
        email: "Email",
        createdAt: "Created",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        status: "Status",
        actions: "Actions",
      },
      actions: {
        menu: "Staff actions",
        markActive: "Mark as active",
        markInactive: "Mark as inactive",
        delete: "Delete staff",
        deleteBlocked: "Cannot delete staff with logged visits or follow-ups",
      },
      deleteConfirm: {
        title: "Delete staff member?",
        description:
          "This permanently removes {name} and revokes their login access. This cannot be undone.",
        confirm: "Delete",
        cancel: "Cancel",
      },
      statusUpdated: "Staff status updated",
      deleted: "Staff member deleted",
      modal: {
        title: "Add Staff Member",
        nameLabel: "Name",
        emailLabel: "Work email",
        employeeIdLabel: "Employee ID",
        passwordLabel: "Password",
        passwordPlaceholder: "Initial sign-in password",
        suggestPassword: "Suggest password",
        passwordHint:
          "Stored securely in auth. Staff sign in at the home page with their work email and this password.",
      },
      active: "Active",
      inactive: "Inactive",
    },
  },
  admin: {
    nav: {
      overview: "Portfolio",
      analytics: "Analytics",
      stores: "Stores",
    },
    analytics: {
      title: "Business Analytics",
      subtitle:
        "Explore performance across stores, customer segments, products, and schemes. All metrics are computed from your live database.",
      filtersTitle: "Filters",
      resetFilters: "Reset",
      filterToggleHint: "Turn on a filter and choose a value, then Apply. Only enabled filters affect the results.",
      filterPlaceholder: "Select value",
      applyFiltersLabel: "Apply filters",
      appliedFiltersTitle: "Active filters",
      noAppliedFiltersLabel: "No dimension filters — showing all visits for the selected time period.",
      naLabel: "N/A",
      visitTypeLabel: "Visit type",
      dateRangeLabel: "Time period",
      tabPresets: "Quick select",
      tabRange: "Range",
      tabDay: "Day",
      tabMonth: "Month",
      tabCompare: "Compare",
      periodALabel: "Current",
      periodBLabel: "Previous",
      applyLabel: "Compare",
      confirmLabel: "Apply",
      rangeSelectionHint: "Select start and end dates",
      daySelectionHint: "Select a date",
      customSectionLabel: "Custom",
      activePeriodLabel: "Showing",
      vsLabel: "vs",
      comparisonTrend: "Daily revenue comparison",
      storeLabel: "Store",
      allStores: "All stores",
      rsoLabel: "RSO / Staff",
      allRso: "All staff",
      segmentLabel: "Customer segment",
      allSegments: "All segments",
      valueTierLabel: "Value tier",
      allValueTiers: "All tiers",
      customerTypeLabel: "Customer type",
      intentLabel: "Intent",
      purchaseStatusLabel: "Purchase status",
      productLabel: "Product category",
      priceLabel: "Price band",
      schemeLabel: "Scheme type",
      enrollmentLabel: "Enrollment outcome",
      sourceLabel: "Visit source",
      genderLabel: "Gender",
      ageLabel: "Age group",
      locationLabel: "Location / area",
      schemeEnrolledLabel: "Scheme enrolled",
      allOptions: "All",
      yesLabel: "Yes",
      noLabel: "No",
      emptyData: "No data matches the selected filters.",
      emptyBreakdown: "No breakdown data for this period.",
      kpis: {
        visits: "Visits",
        revenue: "Revenue",
        conversion: "Conversion rate",
        avgTransaction: "Avg. transaction",
        fieldSales: "Field sales",
        uniqueCustomers: "Unique customers",
      },
      charts: {
        trend: "Revenue trend",
        customerType: "Customer type",
        valueTier: "Value tier",
        intent: "Intent tier",
        purchaseStatus: "Purchase status",
        source: "Visit source",
        productsExplored: "Products explored",
        productsPurchased: "Products purchased",
        schemeProduct: "Schemes pitched",
        enrollment: "Enrollment outcomes",
        gender: "Gender",
        location: "Top locations",
        rsoPerformance: "RSO performance",
      },
      ai: {
        title: "AI insights",
        comingSoon: "Gemini-powered analysis and recommendations will appear here once configured.",
      },
    },
    shell: {
      title: "Consultant Admin",
    },
    overview: {
      title: "Client Store Portfolio",
      subtitle: "Each store is tracked separately — no combined chain metrics.",
      totalStores: "Total Stores",
      activeStores: "Active Stores",
      listedStores: "Showing Stores",
      allCategories: "All categories",
      viewDetails: "View analytics",
      actions: "Actions",
      emptyStores: "No stores match the selected filters.",
    },
    categories: {
      JEWELRY: "Jewelry",
      HANDBAGS: "Handbags",
      WATCHES: "Watches",
      OTHER: "Other",
    },
    storeDetail: {
      backToPortfolio: "Back to portfolio",
      notFound: "Store not found.",
      viewCalls: "Call log",
      viewFieldSales: "Field sales",
      viewStaff: "Staff performance",
      revenueTrend: "Revenue trend",
      sourceBreakdown: "Visit sources",
      purchaseStatusBreakdown: "Purchase outcomes",
      noPurchaseReasons: "Reasons for no purchase",
      noBreakdownData: "No visit data for this period.",
    },
    kpis: {
      totalRevenue: "Revenue",
      totalVisits: "Visits",
      conversionRate: "Conversion Rate",
      activeStores: "Active Stores",
      totalStaff: "Staff",
    },
    stores: {
      title: "Stores Management",
      addStore: "Add Store",
      columns: {
        name: "Store Name",
        category: "Category",
        city: "City",
        pincode: "Pincode",
        staffCount: "Staff Count",
        revenue: "Revenue",
        status: "Status",
      },
      modal: {
        title: "Add Store",
        nameLabel: "Store Name",
        categoryLabel: "Store Category",
        cityLabel: "City",
        stateLabel: "State",
        pincodeLabel: "Pincode",
        pocNameLabel: "POC Name",
        pointOfContactPhoneLabel: "POC Phone",
        customCategoryLabel: "Custom Category",
        customCategoryPlaceholder: "Enter category name",
        emailLabel: "Email",
      },
    },
    staff: {
      title: "Staff Analytics",
      leaderboard: "Top Performers",
      allStores: "All Stores",
      columns: {
        name: "Staff Name",
        store: "Store",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        followUpRate: "Follow-up Rate",
      },
    },
    period: {
      today: "Today",
      week: "This Week",
      month: "This Month",
      last3months: "Last 3 Months",
      last6months: "Last 6 Months",
    },
    deltaPeriod: "vs last period",
    table: {
      active: "Active",
      inactive: "Inactive",
    },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    boundaryTitle: "Something went wrong",
    tryAgain: "Try again",
    unauthorized: "You are not authorised to view this page.",
    notFound: "The requested resource was not found.",
    validation: "Please check the highlighted fields.",
    rateLimited: "Too many requests. Please try again later.",
  },
  empty: {
    visits: "No visits recorded yet",
    followUps: "No follow-ups to show",
    staffCalls: "No customers match these filters",
    portalCalls: "No call activity matches these filters",
    fieldSales: "No field sales match these filters",
    staff: "No staff members found",
    stores: "No stores found",
  },
  portal: {
    allStores: "All stores",
    allStaff: "All staff",
    calls: {
      title: "Call Users",
      subtitle: "Track retention and follow-up calls logged by your team",
      storeFilterLabel: "Store",
      staffFilterLabel: "Staff",
      searchLabel: "Search",
      searchPlaceholder: "Customer name, phone, or staff name",
      yearLabel: "Year",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      queueLabel: "Call queue",
      segmentLabel: "Customer segment",
      valueTierLabel: "Ticket value",
      due: "Due",
      loadError: "Could not load call data. Please refresh and try again.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      notesLabel: "Notes",
      columns: {
        staff: "Staff",
        store: "Store",
      },
      queues: [
        { key: "ALL", label: "All customers" },
        { key: "RETENTION", label: "Retention calls" },
        { key: "FOLLOW_UP", label: "Follow-up calls" },
      ],
      segments: [
        { key: "ALL", label: "All" },
        { key: "NEW", label: "New" },
        { key: "RETAINED", label: "Retained" },
        { key: "PURCHASED", label: "Purchased" },
        { key: "NOT_PURCHASED", label: "Not purchased" },
      ],
      valueTiers: [
        { key: "ALL", label: "All values" },
        { key: "HIGH", label: "High value" },
        { key: "MID", label: "Mid value" },
        { key: "LOW", label: "Low value" },
      ],
      valueTierLabels: {
        HIGH: "High value",
        MID: "Mid value",
        LOW: "Low value",
      },
      intentTierLabels: {
        HOT: "Hot intent",
        WARM: "Warm intent",
        COLD: "Cold intent",
        BROWSING: "Browsing",
      },
      intentFilterActive: "Showing visits with {intent} (from analytics drill-down)",
      purchaseStatusLabels: {
        PURCHASED: "Purchased",
        NOT_PURCHASED: "Not purchased",
        PENDING: "Pending",
      },
      customerTypeLabels: {
        NEW: "New",
        REPEAT: "Retained",
        VIP: "VIP",
      },
      queueStatusLabels: {
        RETENTION: "Retention",
        FOLLOW_UP: "Follow-up",
      },
      callOutcomeLabels: {
        ANSWERED: "Answered",
        NOT_ANSWERED: "Not answered",
        NOT_CALLED: "Not called yet",
      },
    },
    fieldSales: {
      title: "Field Sales",
      subtitle: "Outdoor GHS/GPP enrollment activity logged by your team",
      storeFilterLabel: "Store",
      staffFilterLabel: "Staff",
      searchLabel: "Search",
      searchPlaceholder: "Customer name, phone, or staff name",
      yearLabel: "Year",
      monthLabels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      loadError: "Could not load field sales. Please refresh and try again.",
      previousPage: "Previous",
      nextPage: "Next",
      pageLabel: "Page {page} of {total}",
      notesLabel: "Notes",
      followUpDue: "Follow-up due",
      columns: {
        staff: "Staff",
        store: "Store",
        schemes: "Schemes pitched",
        reason: "Reason",
      },
      analyticsFilterActive: "Filtered from analytics drill-down (outcome or activity type)",
    },
  },
} as const;

export type Content = typeof content;
