export const content = {
  common: {
    appName: "FineSet",
    loading: "Loading…",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    export: "Export",
    search: "Search",
    filter: "Filter",
    noResults: "No results found",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    viewAll: "View all",
    signOut: "Sign out",
  },
  auth: {
    staff: {
      title: "Staff Login",
      subtitle: "Sign in to log customer visits",
      idLabel: "Employee Name",
      idPlaceholder: "Staff Member A",
      passwordLabel: "Employee ID",
      passwordPlaceholder: "EMP001",
      submitLabel: "Sign In",
      errorInvalid: "Invalid employee name or ID",
    },
    store: {
      title: "Store Login",
      subtitle: "Access your store dashboard",
      idLabel: "Store Name",
      idPlaceholder: "Enter store name",
      passwordLabel: "Store Pincode",
      passwordPlaceholder: "Enter store pincode",
      submitLabel: "Access Dashboard",
      errorInvalid: "Invalid store name or pincode",
    },
    admin: {
      title: "Admin Login",
      subtitle: "Chain headquarters access",
      idLabel: "Admin Email",
      idPlaceholder: "admin@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter password",
      submitLabel: "Sign In to Admin",
      errorInvalid: "Invalid admin credentials",
    },
  },
  visitForm: {
    title: "Log Customer Visit",
    subtitle: "Record visit details for analytics",
    progress: "Step {current} of {total}",
    sections: {
      customer: "Customer Details",
      visit: "Visit Details",
      noPurchase: "No-Purchase Context",
      preferences: "Preferences & Schemes",
      followUp: "Follow-up",
    },
    fields: {
      customerName: { label: "Customer Name", placeholder: "Full name" },
      phone: { label: "Phone Number", placeholder: "10-digit mobile" },
      customerType: {
        label: "Customer Type",
        options: { NEW: "New", REPEAT: "Repeat", VIP: "VIP" },
      },
      visitType: {
        label: "Visit Type",
        options: { WALK_IN: "Walk-in", APPOINTMENT: "Appointment" },
      },
      inTime: { label: "In Time", placeholder: "Select time" },
      sourceChannel: {
        label: "Source / Channel",
        options: {
          ORGANIC_WALK_IN: "Organic Walk-in",
          REFERRAL: "Referral",
          SOCIAL_MEDIA: "Social Media",
          INTERNET: "Internet",
          PHONE: "Phone",
          TANISHQ_REF: "Tanishq Reference",
          CARATLANE_REF: "Caratlane Reference",
          OTHER: "Other",
        },
      },
      area: { label: "Area / Locality", placeholder: "Locality or area" },
      gender: {
        label: "Gender",
        options: {
          MALE: "Male",
          FEMALE: "Female",
          OTHER: "Other",
          PREFER_NOT_TO_SAY: "Prefer not to say",
        },
      },
      ageGroup: {
        label: "Age Group",
        options: {
          "18-25": "18–25",
          "26-35": "26–35",
          "36-50": "36–50",
          "50+": "50+",
        },
      },
      productsExplored: {
        label: "Products Explored",
        options: {
          RINGS: "Rings",
          NECKLACES: "Necklaces",
          BANGLES: "Bangles",
          EARRINGS: "Earrings",
          CHAINS: "Chains",
          PENDANTS: "Pendants",
          SETS: "Sets",
          OTHER: "Other",
        },
      },
      purchaseStatus: {
        label: "Purchase Status",
        options: {
          PURCHASED: "Purchased",
          NOT_PURCHASED: "Not Purchased",
          PENDING: "Pending",
        },
      },
      productsPurchased: { label: "Products Purchased" },
      transactionAmount: {
        label: "Transaction Amount",
        placeholder: "Amount in ₹",
      },
      intentTier: {
        label: "Intent Tier",
        options: {
          HOT: "Hot",
          WARM: "Warm",
          COLD: "Cold",
          BROWSING: "Browsing",
        },
      },
      reasonNoPurchase: {
        label: "Reason No Purchase",
        options: {
          BUDGET: "Budget",
          DESIGN_NOT_LIKED: "Design not liked",
          EXPLORING: "Exploring",
          COMPETITOR: "Competitor",
          PAYMENT_ISSUE: "Payment issue",
          WILL_VISIT_AGAIN: "Will visit again",
        },
      },
      competitorMention: {
        label: "Competitor Mention",
        placeholder: "Optional competitor name",
      },
      purchaseOccasion: {
        label: "Purchase Occasion",
        options: {
          WEDDING: "Wedding",
          ANNIVERSARY: "Anniversary",
          GIFT: "Gift",
          SELF: "Self",
          FESTIVAL: "Festival",
        },
      },
      metalKtPref: {
        label: "Metal / KT Preference",
        options: {
          GOLD_18KT: "Gold 18KT",
          GOLD_22KT: "Gold 22KT",
          DIAMOND: "Diamond",
          PLATINUM: "Platinum",
          SILVER: "Silver",
        },
      },
      budgetStated: {
        label: "Budget Stated",
        options: {
          UNDER_15K: "Under ₹15K",
          K15_50K: "₹15K – ₹50K",
          K50_1L: "₹50K – ₹1L",
          ABOVE_1L: "Above ₹1L",
          NOT_STATED: "Not stated",
        },
      },
      schemeEnrolled: { label: "Scheme Enrolled" },
      ghsPolicy: { label: "GHS Policy" },
      followUpNeeded: { label: "Follow-up Needed" },
      followUpDate: { label: "Follow-up Date", placeholder: "Select date" },
      staffNotes: {
        label: "Staff Notes",
        placeholder: "Additional notes (max 500 characters)",
      },
    },
    actions: {
      submit: "Submit Visit",
      logAnother: "Log Another Visit",
      saving: "Saving…",
      successTitle: "Visit logged successfully",
      successMessage: "The visit has been recorded and synced.",
    },
    validation: {
      required: "This field is required",
      phoneInvalid: "Enter a valid 10-digit phone number",
      notesMaxLength: "Notes must be 500 characters or fewer",
      amountRequired: "Transaction amount is required for purchases",
    },
  },
  staff: {
    nav: {
      dashboard: "Log Visit",
    },
    shell: {
      title: "Staff Portal",
    },
  },
  store: {
    nav: {
      overview: "Overview",
      visits: "Visits Log",
      followUp: "Follow-up",
      staff: "Staff",
      analytics: "Analytics",
    },
    shell: {
      title: "Store Dashboard",
    },
    kpis: {
      totalVisits: "Total Visits",
      totalRevenue: "Total Revenue",
      conversionRate: "Conversion Rate",
      avgTransaction: "Avg Transaction",
      newCustomers: "New Customers",
      repeatCustomers: "Repeat Customers",
      openFollowUps: "Open Follow-ups",
    },
    period: {
      today: "Today",
      week: "This Week",
      month: "This Month",
    },
    deltaPeriod: "vs last period",
    table: {
      showing: "Showing {from}–{to} of {total}",
      page: "Page {page}",
      yes: "Yes",
    },
    visits: {
      title: "Visits Log",
      columns: {
        visitId: "Visit ID",
        date: "Date",
        staff: "Staff",
        customer: "Customer",
        phone: "Phone",
        type: "Type",
        status: "Status",
        revenue: "Revenue",
        products: "Products",
        followUp: "Follow-up",
        notes: "Notes",
      },
      detailTitle: "Visit Details",
      exportCsv: "Export CSV",
    },
    followUp: {
      title: "Follow-up Pipeline",
      filters: {
        open: "Open",
        overdue: "Overdue",
        closed: "Closed",
      },
      columns: {
        customer: "Customer",
        phone: "Phone",
        assignedStaff: "Assigned Staff",
        dueDate: "Due Date",
        reason: "Reason",
        lastOutcome: "Last Outcome",
        status: "Status",
      },
      actions: {
        markClosed: "Mark Closed",
        markConverted: "Mark Converted",
      },
    },
    staff: {
      title: "Staff Management",
      addStaff: "Add Staff",
      columns: {
        name: "Name",
        employeeId: "Employee ID",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        status: "Status",
      },
      modal: {
        title: "Add Staff Member",
        nameLabel: "Name",
        employeeIdLabel: "Employee ID",
      },
      active: "Active",
      inactive: "Inactive",
    },
    analytics: {
      title: "Store Analytics",
      insightsTitle: "AI Insights",
      charts: {
        dailyRevenue: "Daily Revenue",
        sourceBreakdown: "Source Channel Breakdown",
        purchaseStatus: "Purchase Status",
        noPurchaseReasons: "No-Purchase Reasons",
      },
    },
  },
  admin: {
    nav: {
      overview: "Overview",
      stores: "Stores",
      staff: "Staff",
      insights: "AI Insights",
      followUp: "Follow-up",
    },
    shell: {
      title: "Master Admin",
    },
    kpis: {
      totalRevenue: "Total Revenue",
      totalVisits: "Total Visits",
      conversionRate: "Conversion Rate",
      activeStores: "Active Stores",
      totalStaff: "Total Staff",
    },
    stores: {
      title: "Stores Management",
      addStore: "Add Store",
      columns: {
        name: "Store Name",
        city: "City",
        pincode: "Pincode",
        staffCount: "Staff Count",
        revenueMtd: "Revenue MTD",
        status: "Status",
      },
      modal: {
        title: "Add Store",
        nameLabel: "Store Name",
        cityLabel: "City",
        stateLabel: "State",
        pincodeLabel: "Pincode",
      },
    },
    staff: {
      title: "Staff Analytics",
      leaderboard: "Top Performers",
      allStores: "All Stores",
      columns: {
        name: "Staff Name",
        store: "Store",
        visits: "Visits",
        revenue: "Revenue",
        conversionRate: "Conversion Rate",
        followUpRate: "Follow-up Rate",
      },
    },
    insights: {
      title: "AI Insights",
      subtitle: "Cross-store intelligence powered by Gemini",
      empty: "No insights available for this period",
      refresh: "Refresh Insights",
    },
    followUp: {
      title: "Follow-up Overview",
      overdueAlert: "Overdue Follow-ups",
      summary: {
        open: "Open Follow-ups",
        overdue: "Overdue",
        converted: "Converted",
      },
      columns: {
        store: "Store",
        customer: "Customer",
        phone: "Phone",
        assignedStaff: "Assigned Staff",
        dueDate: "Due Date",
        reason: "Reason",
      },
    },
    period: {
      today: "Today",
      week: "This Week",
      month: "This Month",
    },
    deltaPeriod: "vs last period",
    table: {
      active: "Active",
      inactive: "Inactive",
    },
    ranking: {
      title: "Store Performance Ranking",
    },
    charts: {
      revenueByStore: "Revenue by Store",
      conversionByStore: "Conversion Rate by Store",
      revenueTrend: "Revenue Trend",
    },
  },
  home: {
    title: "FineSet Jewelry SaaS",
    subtitle: "Multi-portal platform for jewelry store chains",
    portals: {
      staff: { label: "Staff Portal", description: "Log customer visits" },
      store: { label: "Store Portal", description: "Manage store operations" },
      admin: { label: "Admin Portal", description: "Chain-wide analytics" },
      enter: "Enter Portal",
    },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    boundaryTitle: "Something went wrong",
    tryAgain: "Try again",
    unauthorized: "You are not authorised to view this page.",
    notFound: "The requested resource was not found.",
    validation: "Please check the highlighted fields.",
    rateLimited: "Too many requests. Please try again later.",
  },
  empty: {
    visits: "No visits recorded yet",
    followUps: "No follow-ups to show",
    staff: "No staff members found",
    stores: "No stores found",
    insights: "No insights generated yet",
  },
} as const;

export type Content = typeof content;
